### ISSUE TITLE
老大，试了一下不会用

### ISSUE THREAD

**Issue by hehh2001** [rocket049/aria2-trackers#1]
zsh: 权限不够: ./aria2-trackers

sudo: ./aria2-trackers：找不到命令

aria2-trackers: aria2-trackers：无法执行二进制文件

**Comment by rocket049** [comment]
先加上运行权限
chmod +x 文件名

**Comment by hehh2001** [comment]
哦，报歉，如此低级错误也会犯，没仔细看文件权限
