### ISSUE TITLE
预编译版本 exec format error 错误

### ISSUE THREAD

**Issue by QingLeiLi** [rocket049/aria2-trackers#2]
按照 readme 下载的预编译版本，解压执行，报异常

系统：macOS 10.15.1 (19B88)
无 go 环境

```
~ ./aria2-trackers
zsh: exec format error: ./aria2-trackers
```

老板，何解~ 还请多多指教

**Comment by rocket049** [comment]
那是linux amd64环境下的，mac os的请使用go编译器自行编译

**Comment by QingLeiLi** [comment]
OK, Thanks for the nice work.
